//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourApp.Lang_Resource {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Eng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Eng() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TourApp.Lang_Resource.Eng", typeof(Eng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   (5~13) English, Number Combination과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combination {
            get {
                return ResourceManager.GetString("Combination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (8~13) English, Number, Special Character Combination과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Combination2 {
            get {
                return ResourceManager.GetString("Combination2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EngService과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lang_Key {
            get {
                return ResourceManager.GetString("Lang_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select language과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Lang_Select {
            get {
                return ResourceManager.GetString("Lang_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English(영어)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Main Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Main_C {
            get {
                return ResourceManager.GetString("Main_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Middle Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Middle_C {
            get {
                return ResourceManager.GetString("Middle_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   * Necessary과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Necessary {
            get {
                return ResourceManager.GetString("Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   overlap check과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Overlap {
            get {
                return ResourceManager.GetString("Overlap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select region과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Region_Select {
            get {
                return ResourceManager.GetString("Region_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Service classification과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Service {
            get {
                return ResourceManager.GetString("Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Small Category과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Small_C {
            get {
                return ResourceManager.GetString("Small_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   50 Within Character과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Within {
            get {
                return ResourceManager.GetString("Within", resourceCulture);
            }
        }
    }
}
